server:
  port: 8081
  error:
    include-exception: true
    include-stacktrace: always

spring:
  datasource:
    name: tacocloud
    generate-unique-name: false
  thymeleaf:
     cache: false
  security:
     enabled: false
     oauth2:
       resourceserver:
         jwt:
           jwk-set-uri: http://localhost:9000/oauth2/jwks
  data:
     rest:
      base-path: /data-api
  main:
     allow-circular-references: true

#server.port=8443
#server.ssl.key-store=classpath:tomcat.jks
#server.ssl.key-store-password=123456

#logging.file=/var/log/logTaco.log

#logging.level.root=WARN
#org.springframework.security= DEBUG
#logging.file.path=.
logging:
  file: 
    name: TacoCloud.log
  level:
    tacos: WARN

#logging.level.com.examples.springexsecurity.springinaction=TRACE

taco:
 orders:
  pageSize: 2

management: 
    security: 
        enabled: false
         
security:
  ignored: /**

---
spring:
  profiles: prod

  taco:
    orders:
      pageSize: 3
